name: Publish to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.x"
          channel: "stable"
      - uses: erickzanardo/flutter-gh-pages@v3
