name: Publish to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.x"
          channel: "stable"
      - name: Enable Web
        run: flutter config --enable-web
        working-directory: ./example
      - name: Install dependencies
        run: flutter packages get
        working-directory: ./example
      - name: Build Web
        run: flutter build web
        working-directory: ./example
      - name: Deployment
        run: |
          cd example/build/web
          git init
          git config user.name  "Br0w3r"
          git config user.email "gamerbrower@gmail.com"
          git commit -m "Publish WebSite"
          git branch -M main
          git remote add origin https://github.com/Br0w3r/Pokedex-WebSite.git
          git push --force -u origin main
