name: Flutter Web
on: [push]
jobs:
  build:
runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.7.x' # you can use 1.12
        channel: 'stable' # Currently you have to use beta channel for Flutter web.
    - name: Upgrades flutter
      run: flutter upgrade
      working-directory: ./example
    - name: Enable Web
      run: flutter config --enable-web
      working-directory: ./example
    - name: Clear Proyect Flutter
      run: flutter clean
      working-directory: ./example
    - name: Install dependencies
      run: flutter pub get
      working-directory: ./example
    - name: Build Web
      run: flutter build web
      working-directory: ./example
    - name: Deploy
      run: |
        cd example/build/web
        git init
        git config user.name  "Br0w3r"
        git config user.email "gamerbrower@gmail.com"
        git commit -m "Publish WebSite"
        git branch -M main
        git remote add origin https://github.com/Br0w3r/Pokedex-WebSite.git
        git push --force -u origin main