name: Publish to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.x'
          channel: 'stable'
      - uses: erickzanardo/flutter-gh-pages@v3
      - name: Upgrade Flutter
        run: flutter upgrade
      - name: Enable Web
        run: flutter config --enable-web
      - name: Clear Proyect
        run: flutter clean
      - name: Install Dependencies
        run: flutter pub get
      - name: Build Web 
        run: flutter build web
      - name: Deployment
        run: |
          cd example/build/web
          git init
          git config user.name  "Br0w3r"
          git config user.email "gamerbrower@gmail.com"
          git commit -m "Publish WebSite"
          git branch -M main
          git remote add origin https://github.com/Br0w3r/Pokedex-WebSite.git
          git push --force -u origin main 